default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: vegijtha_development
  username: vegijtha
  password: password



test:
  <<: *default
  database: vegijtha_test
  username: vegijtha
  password: password

production:
  <<: *default
  database: vegijtha_production
  username: vegijtha
  password: password
